# syntax=docker/dockerfile:1

# Stage 1: сборка бинарника
FROM golang:1.22 AS builder
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/server ./cmd/server

# Stage 2: минимальный рантайм (nonroot)
FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /app
COPY --from=builder /out/server /server
EXPOSE 8080
ENTRYPOINT ["/server"]
